<?php

/**
 * Lombardia Informatica S.p.A.
 * OPEN 2.0
 *
 *
 * @package    lispa\amos\basic\template
 * @category   CategoryName
 */

class m150728_000008_create_stati extends \yii\db\Migration
{/*
    const TABLE = '{{%italia_regioni}}';

    public function up()
    {
        $sql = "CREATE TABLE `stati` (
                  `id` int(11) NOT NULL,
                  `codice` varchar(5) DEFAULT NULL,
                  `nome` varchar(128) DEFAULT NULL,
                  `created_at` datetime DEFAULT NULL,
                  `created_by` int(11) DEFAULT NULL,
                  `updated_at` datetime DEFAULT NULL,
                  `updated_by` int(11) DEFAULT NULL,
                  `deleted_at` datetime DEFAULT NULL,
                  `deleted_by` int(11) DEFAULT NULL
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
                ALTER TABLE `stati`
                      ADD PRIMARY KEY (`id`),
                      ADD KEY `PRIMARY_KEY` (`id`);
                ";
        $this->execute($sql); 

        $sql = "INSERT INTO `stati` (`id`, `codice`, `nome`, `created_at`, `created_by`, `updated_at`, `updated_by`, `deleted_at`, `deleted_by`) VALUES
                    (1, 'Z200', 'AFGHANISTAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (2, 'Z100', 'ALBANIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (3, 'Z301', 'ALGERIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (4, 'Z101', 'ANDORRA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (5, 'Z302', 'ANGOLA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (6, 'Z529', 'ANGUILLA (ISOLA)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (7, 'Z532', 'ANTIGUA E BARBUDA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (8, 'Z500', 'ANTILLE BRITANNICHE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (9, 'Z501', 'ANTILLE OLANDESI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (10, 'Z203', 'ARABIA SAUDITA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (11, 'Z600', 'ARGENTINA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (12, 'Z252', 'ARMENIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (13, 'Z700', 'AUSTRALIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (14, 'Z102', 'AUSTRIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (15, 'Z253', 'AZERBAIGIAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (16, 'Z502', 'BAHAMA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (17, 'Z204', 'BAHREIN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (18, 'Z249', 'BANGLADESH', NULL, NULL, NULL, NULL, NULL, NULL),
                    (19, 'Z522', 'BARBADOS', NULL, NULL, NULL, NULL, NULL, NULL),
                    (20, 'Z103', 'BELGIO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (21, 'Z512', 'BELIZE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (22, 'Z314', 'BENIN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (23, 'Z400', 'BERMUDA (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (24, 'Z205', 'BHUTAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (25, 'Z139', 'BIELORUSSIA=RUSSIA BIANCA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (26, 'Z206', 'BIRMANIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (27, 'Z601', 'BOLIVIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (28, 'Z153', 'BOSNIA ED ERZEGOVINA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (29, 'Z358', 'BOTSWANA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (30, 'Z602', 'BRASILE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (31, 'Z207', 'BRUNEI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (32, 'Z104', 'BULGARIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (33, 'Z354', 'BURKINA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (34, 'Z305', 'BURUNDI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (35, 'Z208', 'CAMBOGIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (36, 'Z306', 'CAMERUN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (37, 'Z401', 'CANADA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (38, 'Z307', 'CAPO VERDE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (39, 'Z701', 'CAROLINE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (40, 'Z530', 'CAYMAN (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (41, 'Z156', 'CECA REPUBBLICA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (42, 'Z105', 'CECOSLOVACCHIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (43, 'Z308', 'CENTRAFRICANA REPUBBLICA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (44, 'Z702', 'CHRISTMAS (ISOLA)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (45, 'Z309', 'CIAD', NULL, NULL, NULL, NULL, NULL, NULL),
                    (46, 'Z603', 'CILE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (47, 'Z210', 'CINA REPUBBLICA POPOLARE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (48, 'Z211', 'CIPRO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (49, 'Z106', 'CITTA'' DEL VATICANO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (50, 'Z212', 'COCOS (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (51, 'Z604', 'COLOMBIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (52, 'Z310', 'COMORE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (53, 'Z310', 'COMORE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (54, 'Z312', 'CONGO REPUBBLICA DEMOCRATICA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (55, 'Z311', 'CONGO REPUBBLICA POPOLARE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (56, 'Z703', 'COOK (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (57, 'Z214', 'COREA DEL NORD', NULL, NULL, NULL, NULL, NULL, NULL),
                    (58, 'Z213', 'COREA DEL SUD', NULL, NULL, NULL, NULL, NULL, NULL),
                    (59, 'Z313', 'COSTA D''AVORIO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (60, 'Z503', 'COSTA RICA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (61, 'Z149', 'CROAZIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (62, 'Z504', 'CUBA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (63, 'Z107', 'DANIMARCA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (64, 'Z900', 'DIPENDENZE AUSTRALIANE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (65, 'Z901', 'DIPENDENZE BRITANNICHE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (66, 'Z800', 'DIPENDENZE CANADESI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (67, 'Z902', 'DIPENDENZE FRANCESI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (68, 'Z903', 'DIPENDENZE NEOZELANDESI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (69, 'Z904', 'DIPENDENZE NORVEGESI ANTARTICHE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (70, 'Z801', 'DIPENDENZE NORVEGESI ARTICHE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (71, 'Z802', 'DIPENDENZE RUSSE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (72, 'Z905', 'DIPENDENZE STATUNITENSI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (73, 'Z906', 'DIPENDENZE SUDAFRICANE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (74, 'Z526', 'DOMINICA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (75, 'Z505', 'DOMINICANA REPUBBLICA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (76, 'Z605', 'ECUADOR', NULL, NULL, NULL, NULL, NULL, NULL),
                    (77, 'Z336', 'EGITTO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (78, 'Z506', 'EL SALVADOR', NULL, NULL, NULL, NULL, NULL, NULL),
                    (79, 'Z215', 'EMIRATI ARABI UNITI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (80, 'Z368', 'ERITREA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (81, 'Z144', 'ESTONIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (82, 'Z315', 'ETIOPIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (83, 'Z108', 'FAER OER (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (84, 'Z704', 'FIGI=VITI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (85, 'Z216', 'FILIPPINE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (86, 'Z109', 'FINLANDIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (87, 'Z110', 'FRANCIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (88, 'Z316', 'GABON', NULL, NULL, NULL, NULL, NULL, NULL),
                    (89, 'Z317', 'GAMBIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (90, 'Z218', 'GAZA (TERRITORIO DI)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (91, 'Z254', 'GEORGIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (92, 'Z112', 'GERMANIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (93, 'Z318', 'GHANA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (94, 'Z507', 'GIAMAICA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (95, 'Z219', 'GIAPPONE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (96, 'Z113', 'GIBILTERRA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (97, 'Z361', 'GIBUTI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (98, 'Z705', 'GILBERT E ELLICE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (99, 'Z220', 'GIORDANIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (100, 'Z114', 'GRAN BRETAGNA E IRLANDA DEL NORD', NULL, NULL, NULL, NULL, NULL, NULL),
                    (101, 'Z115', 'GRECIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (102, 'Z524', 'GRENADA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (103, 'Z402', 'GROENLANDIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (104, 'Z508', 'GUADALUPA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (105, 'Z706', 'GUAM (ISOLA)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (106, 'Z509', 'GUATEMALA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (107, 'Z607', 'GUAYANA=GUIANA FRANCESE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (108, 'Z319', 'GUINEA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (109, 'Z320', 'GUINEA BISSAU', NULL, NULL, NULL, NULL, NULL, NULL),
                    (110, 'Z321', 'GUINEA EQUATORIALE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (111, 'Z606', 'GUYANA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (112, 'Z510', 'HAITI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (113, 'Z511', 'HONDURAS', NULL, NULL, NULL, NULL, NULL, NULL),
                    (114, 'Z222', 'INDIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (115, 'Z223', 'INDONESIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (116, 'Z224', 'IRAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (117, 'Z225', 'IRAQ', NULL, NULL, NULL, NULL, NULL, NULL),
                    (118, 'Z707', 'IRIAN OCCIDENTALE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (119, 'Z116', 'IRLANDA=EIRE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (120, 'Z117', 'ISLANDA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (121, 'Z721', 'ISOLE CILENE (PASQUA E SALA Y GOMEZ)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (122, 'Z226', 'ISRAELE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (123, '', 'ITALIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (124, 'Z118', 'IUGOSLAVIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (125, 'Z255', 'KAZAKISTAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (126, 'Z322', 'KENYA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (127, 'Z256', 'KIRGHIZISTAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (128, 'Z731', 'KIRIBATI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (129, 'Z160', 'KOSSOVO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (130, 'Z227', 'KUWAIT', NULL, NULL, NULL, NULL, NULL, NULL),
                    (131, 'Z324', 'LA REUNION (ISOLA)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (132, 'Z228', 'LAOS', NULL, NULL, NULL, NULL, NULL, NULL),
                    (133, 'Z359', 'LESOTHO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (134, 'Z145', 'LETTONIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (135, 'Z229', 'LIBANO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (136, 'Z325', 'LIBERIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (137, 'Z326', 'LIBIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (138, 'Z119', 'LIECHTENSTEIN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (139, 'Z146', 'LITUANIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (140, 'Z120', 'LUSSEMBURGO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (141, 'Z231', 'MACAO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (142, 'Z148', 'MACEDONIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (143, 'Z708', 'MACQUARIE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (144, 'Z327', 'MADAGASCAR', NULL, NULL, NULL, NULL, NULL, NULL),
                    (145, 'Z328', 'MALAWI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (146, 'Z230', 'MALAYSIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (147, 'Z232', 'MALDIVE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (148, 'Z329', 'MALI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (149, 'Z121', 'MALTA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (150, 'Z609', 'MALVINE=FALKLAND (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (151, 'Z122', 'MAN (ISOLA)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (152, 'Z710', 'MARIANNE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (153, 'Z330', 'MAROCCO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (154, 'Z711', 'MARSHALL', NULL, NULL, NULL, NULL, NULL, NULL),
                    (155, 'Z513', 'MARTINICA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (156, 'Z331', 'MAURITANIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (157, 'Z332', 'MAURIZIO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (158, 'Z360', 'MAYOTTE (ISOLA)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (159, 'Z514', 'MESSICO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (160, 'Z735', 'MICRONESIA STATI FEDERATI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (161, 'Z712', 'MIDWAY (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (162, 'Z140', 'MOLDAVIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (163, 'Z123', 'MONACO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (164, 'Z233', 'MONGOLIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (165, 'Z159', 'MONTENEGRO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (166, 'Z531', 'MONTSERRAT', NULL, NULL, NULL, NULL, NULL, NULL),
                    (167, 'Z333', 'MOZAMBICO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (168, 'Z300', 'NAMIBIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (169, 'Z713', 'NAURU', NULL, NULL, NULL, NULL, NULL, NULL),
                    (170, 'Z234', 'NEPAL', NULL, NULL, NULL, NULL, NULL, NULL),
                    (171, 'Z515', 'NICARAGUA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (172, 'Z334', 'NIGER', NULL, NULL, NULL, NULL, NULL, NULL),
                    (173, 'Z335', 'NIGERIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (174, 'Z714', 'NIUE=SAVAGE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (175, 'Z715', 'NORFOLK (ISOLE E ISOLE DEL MAR DEI CORALLI)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (176, 'Z124', 'NORMANNE (ISOLE)=ISOLE DEL CANALE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (177, 'Z125', 'NORVEGIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (178, 'Z716', 'NUOVA CALEDONIA (ISOLE E DIPENDENZE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (179, 'Z719', 'NUOVA ZELANDA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (180, 'Z235', 'OMAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (181, 'Z126', 'PAESI BASSI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (182, 'Z236', 'PAKISTAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (183, 'Z734', 'PALAU', NULL, NULL, NULL, NULL, NULL, NULL),
                    (184, 'Z516', 'PANAMA''', NULL, NULL, NULL, NULL, NULL, NULL),
                    (185, 'Z517', 'PANAMA ZONA DEL CANALE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (186, 'Z730', 'PAPUA NUOVA GUINEA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (187, 'Z610', 'PARAGUAY', NULL, NULL, NULL, NULL, NULL, NULL),
                    (188, 'Z611', 'PERU''', NULL, NULL, NULL, NULL, NULL, NULL),
                    (189, 'Z722', 'PITCAIRN (E DIPENDENZE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (190, 'Z723', 'POLINESIA FRANCESE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (191, 'Z128', 'PORTOGALLO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (192, 'Z518', 'PUERTO RICO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (193, 'Z237', 'QATAR', NULL, NULL, NULL, NULL, NULL, NULL),
                    (194, 'Z217', 'REPUBBLICA DELLA CINA NAZIONALE=TAIWAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (195, 'Z127', 'REPUBBLICA DI POLONIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (196, 'Z129', 'ROMANIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (197, 'Z338', 'RUANDA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (198, 'Z154', 'RUSSIA=FEDERAZIONE RUSSA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (199, 'Z339', 'SAHARA SPAGNOLO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (200, 'Z533', 'SAINT KITTS E NEVIS=SAINT CHRISTOPHER E NEVIS', NULL, NULL, NULL, NULL, NULL, NULL),
                    (201, 'Z527', 'SAINT LUCIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (202, 'Z403', 'SAINT PIERRE ET MIQUELON (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (203, 'Z528', 'SAINT VINCENT E GRENADINE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (204, 'Z724', 'SALOMONE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (205, 'Z726', 'SAMOA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (206, 'Z725', 'SAMOA AMERICANE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (207, 'Z130', 'SAN MARINO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (208, 'Z340', 'SANT''ELENA (ISOLA)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (209, 'Z341', 'SAO TOME'' E PRINCIPE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (210, 'Z342', 'SEICELLE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (211, 'Z342', 'SEICELLE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (212, 'Z343', 'SENEGAL', NULL, NULL, NULL, NULL, NULL, NULL),
                    (213, 'Z158', 'SERBIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (214, 'Z344', 'SIERRA LEONE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (215, 'Z248', 'SINGAPORE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (216, 'Z240', 'SIRIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (217, 'Z155', 'SLOVACCHIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (218, 'Z150', 'SLOVENIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (219, 'Z345', 'SOMALIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (220, 'Z131', 'SPAGNA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (221, 'Z209', 'SRI LANKA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (222, 'Z404', 'STATI UNITI D''AMERICA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (223, 'Z907', 'SUD SUDAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (224, 'Z347', 'SUDAFRICANA REPUBBLICA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (225, 'Z348', 'SUDAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (226, 'Z608', 'SURINAME', NULL, NULL, NULL, NULL, NULL, NULL),
                    (227, 'Z132', 'SVEZIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (228, 'Z133', 'SVIZZERA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (229, 'Z349', 'SWAZILAND', NULL, NULL, NULL, NULL, NULL, NULL),
                    (230, 'Z257', 'TAGIKISTAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (231, 'Z357', 'TANZANIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (232, 'Z161', 'TERRITORI PALESTINESI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (233, 'Z241', 'THAILANDIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (234, 'Z351', 'TOGO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (235, 'Z727', 'TOKELAU=ISOLE DELL''UNIONE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (236, 'Z728', 'TONGA=ISOLE DEGLI AMICI', NULL, NULL, NULL, NULL, NULL, NULL),
                    (237, 'Z612', 'TRINIDAD E TOBAGO', NULL, NULL, NULL, NULL, NULL, NULL),
                    (238, 'Z352', 'TUNISIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (239, 'Z243', 'TURCHIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (240, 'Z258', 'TURKEMENISTAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (241, 'Z519', 'TURKS E CAICOS (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (242, 'Z732', 'TUVALU', NULL, NULL, NULL, NULL, NULL, NULL),
                    (243, 'Z138', 'UCRAINA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (244, 'Z353', 'UGANDA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (245, 'Z134', 'UNGHERIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (246, 'Z135', 'UNIONE REPUBBLICHE SOCIALISTE SOVIETICHE', NULL, NULL, NULL, NULL, NULL, NULL),
                    (247, 'Z613', 'URUGUAY', NULL, NULL, NULL, NULL, NULL, NULL),
                    (248, 'Z259', 'UZBEKISTAN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (249, 'Z733', 'VANUATU', NULL, NULL, NULL, NULL, NULL, NULL),
                    (250, 'Z614', 'VENEZUELA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (251, 'Z520', 'VERGINI AMERICANE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (252, 'Z525', 'VERGINI BRITANNICHE (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (253, 'Z251', 'VIETNAM', NULL, NULL, NULL, NULL, NULL, NULL),
                    (254, 'Z729', 'WALLIS E FUTUNA (ISOLE)', NULL, NULL, NULL, NULL, NULL, NULL),
                    (255, 'Z246', 'YEMEN', NULL, NULL, NULL, NULL, NULL, NULL),
                    (256, 'Z355', 'ZAMBIA', NULL, NULL, NULL, NULL, NULL, NULL),
                    (257, 'Z337', 'ZIMBABWE', NULL, NULL, NULL, NULL, NULL, NULL);";
        $this->execute($sql);

    }

    public function down()
    {

        $this->dropTable('stati');

    }
*/
}